name: Build, publish, and deploy Frontend Docker image (ECR) to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t backend-repo .

      - name: Tag Docker image
        run: docker tag backend-repo:latest 879602785537.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 879602785537.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # Authenticate Docker to ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 879602785537.dkr.ecr.us-east-1.amazonaws.com

            # Pull the latest Docker image from ECR
            docker pull 879602785537.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest

            # Stop and remove old container if it exists
            docker stop backend || true
            docker rm backend || true

            # Run new container
            docker run -d --name backend -p 5001:5001 879602785537.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
